In [10]:
import pandas as pd
import ast
import json

In [11]:
df=pd.read_csv("movies_metadata.csv",sep=',', low_memory=False)

In [25]:
df.shape

(45436, 24)

In [26]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{""id"": 10194, ""name"": ""Toy Story Collection"", ...",30000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 35, ""...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,None,Toy Story,False,7.7,5415.0
1,False,None,65000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",None,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{""id"": 119050, ""name"": ""Grumpy Old Men Collect...",0,"[{""id"": 10749, ""name"": ""Romance""}, {""id"": 35, ...",None,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,None,16000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",None,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{""id"": 96871, ""name"": ""Father of the Bride Col...",0,"[{""id"": 35, ""name"": ""Comedy""}]",None,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [13]:
def convert_to_json(value):
    try:
        if pd.isna(value) or value == '':
            return None
        # ast.literal_eval safely parses Python dict/list strings
        parsed = ast.literal_eval(value)
        return json.dumps(parsed)   # convert to proper JSON string
    except:
        return value  # return as-is if parsing fails

In [14]:
json_columns = [
    'belongs_to_collection',
    'genres',
    'production_companies',
    'production_countries',
    'spoken_languages'
]

In [15]:
for col in json_columns:
    df[col] = df[col].apply(convert_to_json)

In [17]:
string_columns = [
    'original_language', 'original_title', 'title',
    'overview', 'tagline', 'status', 'homepage',
    'imdb_id', 'poster_path', 'release_date'
]

In [18]:
for col in string_columns:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace('nan', None)

In [19]:
df = df.dropna(subset=['id'])           # remove rows with no ID
df = df.drop_duplicates(subset=['id'])  # remove duplicate movies

In [27]:
del_col=[
    'belongs_to_collection',
    'homepage',
    'imdb_id',
    'popularity',
    'video',
    'vote_count'
]

In [28]:
df=df.drop(columns=del_col)

In [32]:
df.columns

Index(['adult', 'budget', 'genres', 'id', 'original_language',
       'original_title', 'overview', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average'],
      dtype='object')

In [33]:
df.head()

,adult,budget,genres,id,original_language,original_title,overview,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average
0,False,30000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 35, ""...",862,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{""name"": ""Pixar Animation Studios"", ""id"": 3}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1995-10-30,373554033.0,81.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,None,Toy Story,7.7
1,False,65000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",8844,en,Jumanji,When siblings Judy and Peter discover an encha...,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{""name"": ""TriStar Pictures"", ""id"": 559}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1995-12-15,262797249.0,104.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Roll the dice and unleash the excitement!,Jumanji,6.9
2,False,0,"[{""id"": 10749, ""name"": ""Romance""}, {""id"": 35, ...",15602,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1995-12-22,0.0,101.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5
3,False,16000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",31357,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,"[{""name"": ""Twentieth Century Fox Film Corporat...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1995-12-22,81452156.0,127.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1
4,False,0,"[{""id"": 35, ""name"": ""Comedy""}]",11862,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{""name"": ""Sandollar Productions"", ""id"": 5842}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1995-02-10,76578911.0,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7

In [34]:
df.to_csv('movies_clean.csv', index=False, quoting=1)